size_class_id_to_description:
  '00':  'All size classes'
  '01':  '1 to 4 employees'
  '02':  '5 to 9 employees'
  '03':  '10 to 19 employees'
  '04':  '20 to 49 employees'
  '05':  '50 to 99 employees'
  '06':  '100 to 249 employees'
  '07':  '250 to 499 employees'
  '08':  '500 to 999 employees'
  '09':  '1,000 or more employees'
  '10':  '1 job'
  '11':  '2 jobs'
  '12':  '3 jobs'
  '13':  '4 jobs'
  '14':  '5 jobs'
  '15':  '6 jobs'
  '16':  '7 jobs'
  '17':  '8 jobs'
  '18':  '9 jobs'
  '19':  '10 jobs'
  '20':  '11-14 jobs'
  '21':  '15-19 jobs'
  '22':  '20-24 jobs'
  '23':  '25-29 jobs'
  '24':  '30-39 jobs'
  '25':  '40-49 jobs'
  '26':  '50-74 jobs'
  '27':  '75-99 jobs'
  '28':  '100 or more jobs'
  '31':  '1 to 4 jobs'
  '32':  '5 to 19 jobs'
  '33':  '20 or more jobs'

industry_code_to_naics:
  '100010': '11'
  '100020': '23'
  '100030': '31'
  '200010': '42'
  '200020': '44'
  '200030': '48'
  '200040': '22'
  '200050': '51'
  '200060': '52'
  '200070': '54'
  '200080': '61'
  '200090': '71'
  '200100': '81'
  '300111': '111'
  '300112': '112'
  '300113': '113'
  '300114': '114'
  '300115': '115'
  '300211': '211'
  '300212': '212'
  '300213': '213'
  '300236': '236'
  '300237': '237'
  '300238': '238'
  '300311': '311'
  '300312': '312'
  '300313': '313'
  '300314': '314'
  '300315': '315'
  '300316': '316'
  '300321': '321'
  '300322': '322'
  '300323': '323'
  '300324': '324'
  '300325': '325'
  '300326': '326'
  '300327': '327'
  '300331': '331'
  '300332': '332'
  '300333': '333'
  '300334': '334'
  '300335': '335'
  '300336': '336'
  '300337': '337'
  '300339': '339'
  '300423': '423'
  '300424': '424'
  '300425': '425'
  '300441': '441'
  '300442': '442'
  '300443': '443'
  '300444': '444'
  '300445': '445'
  '300446': '446'
  '300447': '447'
  '300448': '448'
  '300451': '451'
  '300452': '452'
  '300453': '453'
  '300454': '454'
  '300481': '481'
  '300483': '483'
  '300484': '484'
  '300485': '485'
  '300486': '486'
  '300487': '487'
  '300488': '488'
  '300492': '492'
  '300493': '493'
  '300511': '511'
  '300512': '512'
  '300515': '515'
  '300517': '517'
  '300518': '518'
  '300519': '519'
  '300522': '522'
  '300523': '523'
  '300524': '524'
  '300525': '525'
  '300531': '531'
  '300532': '532'
  '300533': '533'
  '300541': '541'
  '300551': '551'
  '300561': '561'
  '300562': '562'
  '300611': '611'
  '300621': '621'
  '300622': '622'
  '300623': '623'
  '300624': '624'
  '300711': '711'
  '300712': '712'
  '300713': '713'
  '300721': '721'
  '300722': '722'
  '300811': '811'
  '300812': '812'
  '300813': '813'

descriptions:
  'employment': 'The Business Employment Dynamics statistics measure the net change in employment at the establishment level. These changes come about in one of four ways. A net increase in employment can come from either opening establishments or expanding establishments. A net decrease in employment can come from either closing establishments or contracting establishments. Gross job gains include the sum of all jobs added at either opening or expanding establishments. Gross job losses include the sum of all jobs lost in either closing or contracting establishments. The net change in employment is the difference between gross job gains and gross job losses.'

  'openings_short': 'Openings include both new startups (births) and reopenings of the existing seasonal establishments that reported zero employment in the previous quarter. Closings include establishments that go out of business permanently (deaths), as well as seasonal businesses that shut down temporarily.'

  'openings_long': 'Openings are defined as those establishments that had positive employment for the first time in the third month of the current quarter with no link to the previous quarter, or had positive employment in the current quarter and zero or no employment in the previous quarter. "Zero employment” means that an employment level of zero was reported, whereas “no employment” means that there were not any employment numbers reported at all.'

  'establishments_long': 'An establishment represents an economic unit that produces goods and services, usually at a single location, and engages in only one or predominantly one activity. A firm, on the other hand, may consist of several establishments. When an establishment opens for business for the first time, it is counted as an establishment birth, a State-level firm birth, and a national-level firm birth. If the firm in question opens another establishment, this will be counted as another establishment birth and as a firm-level expansion. If that establishment is in another State, it also will be a counted as a State-level firm birth. '
