SOURCES = [
  { name: 'Bureau of Economic Analysis', internal_name: 'bea', datasets_attributes: [
    { name: 'Fixed Assets', internal_name: 'fixed_assets', external_tables_attributes: [
      { external_id: 16, external_name: "Table 1.1. Current-Cost Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 17, external_name: "Table 1.2. Chain-Type Quantity Indexes for Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 86, external_name: "Table 1.3. Current-Cost Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 87, external_name: "Table 1.4. Chain-Type Quantity Indexes for Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 96, external_name: "Table 1.5. Investment in Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 97, external_name: "Table 1.6. Chain-Type Quantity Indexes for Investment in Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 105, external_name: "Table 1.7. Current-Cost Other Changes in Volume of Assets for Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 124, external_name: "Table 1.8. Historical-Cost Other Changes in Volume of Assets for Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 125, external_name: "Table 1.9. Current-Cost Average Age at Yearend of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 18, external_name: "Table 2.1. Current-Cost Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 19, external_name: "Table 2.2. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 42, external_name: "Table 2.3. Historical-Cost Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 65, external_name: "Table 2.4. Current-Cost Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 66, external_name: "Table 2.5. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 67, external_name: "Table 2.6. Historical-Cost Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 51, external_name: "Table 2.7. Investment in Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 52, external_name: "Table 2.8. Chain-Type Quantity Indexes for Investment in Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 106, external_name: "Table 2.9. Current-Cost Average Age at Yearend of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 107, external_name: "Table 2.10. Historical-Cost Average Age at Yearend of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 21, external_name: "Table 3.1E. Current-Cost Net Stock of Private Equipment by Industry (A)" },
      { external_id: 126, external_name: "Table 3.1ESI. Current-Cost Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 127, external_name: "Table 3.1I. Current-Cost Net Stock of Intellectual Property Products by Industry (A)" },
      { external_id: 22, external_name: "Table 3.1S. Current-Cost Net Stock of Private Structures by Industry (A)" },
      { external_id: 24, external_name: "Table 3.2E. Chain-Type Quantity Indexes for Net Stock of Private Equipment by Industry (A)" },
      { external_id: 128, external_name: "Table 3.2ESI. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 129, external_name: "Table 3.2I. Chain-Type Quantity Indexes for Net Stock of Intellectual Property Products by Industry (A)" },
      { external_id: 25, external_name: "Table 3.2S. Chain-Type Quantity Indexes for Net Stock of Private Structures by Industry (A)" },
      { external_id: 44, external_name: "Table 3.3E. Historical-Cost Net Stock of Private Equipment by Industry (A)" },
      { external_id: 130, external_name: "Table 3.3ESI. Historical-Cost Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 131, external_name: "Table 3.3I. Historical-Cost Net Stock of Private Intellectual Property Products by Industry (A)" },
      { external_id: 45, external_name: "Table 3.3S. Historical-Cost Net Stock of Private Structures by Industry (A)" },
      { external_id: 69, external_name: "Table 3.4E. Current-Cost Depreciation of Private Equipment by Industry (A)" },
      { external_id: 132, external_name: "Table 3.4ESI. Current-Cost Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 133, external_name: "Table 3.4I. Current-Cost Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 70, external_name: "Table 3.4S. Current-Cost Depreciation of Private Structures by Industry (A)" },
      { external_id: 72, external_name: "Table 3.5E. Chain-Type Quantity Indexes for Depreciation of Private Equipment by Industry (A)" },
      { external_id: 134, external_name: "Table 3.5ESI. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 135, external_name: "Table 3.5I. Chain-Type Quantity Indexes for Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 73, external_name: "Table 3.5S. Chain-Type Quantity Indexes for Depreciation of Private Structures by Industry (A)" },
      { external_id: 75, external_name: "Table 3.6E. Historical-Cost Depreciation of Private Equipment by Industry (A)" },
      { external_id: 136, external_name: "Table 3.6ESI. Historical-Cost Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 137, external_name: "Table 3.6I. Historical-Cost Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 76, external_name: "Table 3.6S. Historical-Cost Depreciation of Private Structures by Industry (A)" },
      { external_id: 54, external_name: "Table 3.7E. Investment in Private Equipment by Industry (A)" },
      { external_id: 138, external_name: "Table 3.7ESI. Investment in Private Fixed Assets by Industry (A)" },
      { external_id: 139, external_name: "Table 3.7I. Investment in Private Intellectual Property Products by Industry (A)" },
      { external_id: 55, external_name: "Table 3.7S. Investment in Private Structures by Industry (A)" },
      { external_id: 57, external_name: "Table 3.8E. Chain-Type Quantity Indexes for Investment in Private Equipment by Industry (A)" },
      { external_id: 140, external_name: "Table 3.8ESI. Chain-Type Quantity Indexes for Investment in Private Fixed Assets by Industry (A)" },
      { external_id: 141, external_name: "Table 3.8I. Chain-Type Quantity Indexes for Investment in Private Intellectual Property Products by Industry (A)" },
      { external_id: 58, external_name: "Table 3.8S. Chain-Type Quantity Indexes for Investment in Private Structures by Industry (A)" },
      { external_id: 108, external_name: "Table 3.9E. Current-Cost Average Age at Yearend of Private Equipment by Industry (A)" },
      { external_id: 142, external_name: "Table 3.9ESI. Current-Cost Average Age at Yearend of Private Fixed Assets by Industry (A)" },
      { external_id: 143, external_name: "Table 3.9I. Current-Cost Average Age at Yearend of Private Intellectual Property Products by Industry (A)" },
      { external_id: 110, external_name: "Table 3.9S. Current-Cost Average Age at Yearend of Private Structures by Industry (A)" },
      { external_id: 111, external_name: "Table 3.10E. Historical-Cost Average Age at Yearend of Private Equipment by Industry (A)" },
      { external_id: 144, external_name: "Table 3.10ESI. Historical-Cost Average Age at Yearend of Private Fixed Assets by Industry (A)" },
      { external_id: 145, external_name: "Table 3.10I. Historical-Cost Average Age at Yearend of Private Intellectual Property Products by Industry (A)" },
      { external_id: 113, external_name: "Table 3.10S. Historical-Cost Average Age at Yearend of Private Structures by Industry (A)" },
      { external_id: 26, external_name: "Table 4.1. Current-Cost Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 27, external_name: "Table 4.2. Chain-Type Quantity Indexes for Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 46, external_name: "Table 4.3. Historical-Cost Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 77, external_name: "Table 4.4. Current-Cost Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 78, external_name: "Table 4.5. Chain-Type Quantity Indexes for Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 79, external_name: "Table 4.6. Historical-Cost Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 59, external_name: "Table 4.7. Investment in Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 60, external_name: "Table 4.8. Chain-Type Quantity Indexes for Investment in Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 114, external_name: "Table 4.9. Current-Cost Average Age at Yearend of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 115, external_name: "Table 4.10. Historical-Cost Average Age at Yearend of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 28, external_name: "Table 5.1. Current-Cost Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 29, external_name: "Table 5.2. Chain-Type Quantity Indexes for Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 47, external_name: "Table 5.3. Historical-Cost Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 88, external_name: "Table 5.4. Current-Cost Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 89, external_name: "Table 5.5. Chain-Type Quantity Indexes for Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 90, external_name: "Table 5.6. Historical-Cost Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 98, external_name: "Table 5.7. Investment in Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 99, external_name: "Table 5.8. Chain-Type Quantity Indexes for Investment in Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 116, external_name: "Table 5.9. Current-Cost Average Age at Yearend of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 117, external_name: "Table 5.10. Historical-Cost Average Age at Yearend of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 41, external_name: "Table 6.1. Current-Cost Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 48, external_name: "Table 6.2. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 49, external_name: "Table 6.3. Historical-Cost Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 80, external_name: "Table 6.4. Current-Cost Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 81, external_name: "Table 6.5. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 82, external_name: "Table 6.6. Historical-Cost Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 61, external_name: "Table 6.7. Investment in Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 62, external_name: "Table 6.8. Chain-Type Quantity Indexes for Investment in Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 118, external_name: "Table 6.9. Current-Cost Average Age at Yearend of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 119, external_name: "Table 6.10. Historical-Cost Average Age at Yearend of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 35, external_name: "Table 7.1A. Current-Cost Net Stock of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 30, external_name: "Table 7.1B. Current-Cost Net Stock of Government Fixed Assets (A)" },
      { external_id: 36, external_name: "Table 7.2A. Chain-Type Quantity Indexes for Net Stock of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 31, external_name: "Table 7.2B. Chain-Type Quantity Indexes for Net Stock of Government Fixed Assets (A)" },
      { external_id: 91, external_name: "Table 7.3A. Current-Cost Depreciation of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 92, external_name: "Table 7.3B. Current-Cost Depreciation of Government Fixed Assets (A)" },
      { external_id: 93, external_name: "Table 7.4A. Chain-Type Quantity Indexes for Depreciation of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 94, external_name: "Table 7.4B. Chain-Type Quantity Indexes for Depreciation of Government Fixed Assets (A)" },
      { external_id: 100, external_name: "Table 7.5A. Investment in Government Fixed Assets, 1901-1996 (A)" },
      { external_id: 101, external_name: "Table 7.5B. Investment in Government Fixed Assets (A)" },
      { external_id: 102, external_name: "Table 7.6A. Chain-Type Quantity Indexes for Investment in Government Fixed Assets, 1901-1996 (A)" },
      { external_id: 103, external_name: "Table 7.6B. Chain-Type Quantity Indexes for Investment in Government Fixed Assets (A)" },
      { external_id: 120, external_name: "Table 7.7A. Current-Cost Average Age at Yearend of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 121, external_name: "Table 7.7B. Current-Cost Average Age at Yearend of Government Fixed Assets (A)" },
      { external_id: 32, external_name: "Table 8.1. Current-Cost Net Stock of Consumer Durable Goods (A)" },
      { external_id: 33, external_name: "Table 8.2. Chain-Type Quantity Indexes for Net Stock of Consumer Durable Goods (A)" },
      { external_id: 50, external_name: "Table 8.3. Historical-Cost Net Stock of Consumer Durable Goods (A)" },
      { external_id: 83, external_name: "Table 8.4. Current-Cost Depreciation of Consumer Durable Goods (A)" },
      { external_id: 84, external_name: "Table 8.5. Chain-Type Quantity Indexes for Depreciation of Consumer Durable Goods (A)" },
      { external_id: 85, external_name: "Table 8.6. Historical-Cost Depreciation of Consumer Durable Goods (A)" },
      { external_id: 63, external_name: "Table 8.7. Investment in Consumer Durable Goods (A)" },
      { external_id: 64, external_name: "Table 8.8. Chain-Type Quantity Indexes for Investment in Consumer Durable Goods (A)" },
      { external_id: 122, external_name: "Table 8.9. Current-Cost Average Age at Yearend of Consumer Durable Goods (A)" },
      { external_id: 123, external_name: "Table 8.10. Historical-Cost Average Age at Yearend of Consumer Durable Goods (A)" },
      { external_id: 34, external_name: "Table 9.1. Real Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 95, external_name: "Table 9.2. Real Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 104, external_name: "Table 9.3. Real Investment in Fixed Assets and Consumer Durable Goods (A)" }]
    },
    { name: 'NIPA (National Income and Product Accounts)', internal_name: 'nipa', external_tables_attributes: [
      { external_id: 1, external_name: "Table 1.1.1. Percent Change From Preceding Period in Real Gross Domestic Product (A) (Q)" },
      { external_id: 2, external_name: "Table 1.1.2. Contributions to Percent Change in Real Gross Domestic Product (A) (Q)" },
      { external_id: 3, external_name: "Table 1.1.3. Real Gross Domestic Product, Quantity Indexes (A) (Q)" },
      { external_id: 4, external_name: "Table 1.1.4. Price Indexes for Gross Domestic Product (A) (Q)" },
      { external_id: 5, external_name: "Table 1.1.5. Gross Domestic Product (A) (Q)" },
      { external_id: 6, external_name: "Table 1.1.6. Real Gross Domestic Product, Chained Dollars (A) (Q)" },
      { external_id: 7, external_name: "Table 1.1.6A. Real Gross Domestic Product, Chained (1937) Dollars (A)" },
      { external_id: 8, external_name: "Table 1.1.6B. Real Gross Domestic Product, Chained (1952) Dollars (A) (Q)" },
      { external_id: 9, external_name: "Table 1.1.6C. Real Gross Domestic Product, Chained (1972) Dollars (A) (Q)" },
      { external_id: 10, external_name: "Table 1.1.6D. Real Gross Domestic Product, Chained (1987) Dollars (A) (Q)" },
      { external_id: 11, external_name: "Table 1.1.7. Percent Change From Preceding Period in Prices for Gross Domestic Product (A) (Q)" },
      { external_id: 12, external_name: "Table 1.1.8. Contributions to Percent Change in the Gross Domestic Product Price Index (A) (Q)" },
      { external_id: 13, external_name: "Table 1.1.9. Implicit Price Deflators for Gross Domestic Product (A) (Q)" },
      { external_id: 14, external_name: "Table 1.1.10. Percentage Shares of Gross Domestic Product (A) (Q)" },
      { external_id: 310, external_name: "Table 1.1.11. Real Gross Domestic Product: Percent Change From Quarter One Year Ago (Q)" },
      { external_id: 15, external_name: "Table 1.2.1. Percent Change From Preceding Period in Real Gross Domestic Product by Major Type of Product (A) (Q)" },
      { external_id: 16, external_name: "Table 1.2.2. Contributions to Percent Change in Real Gross Domestic Product by Major Type of Product (A) (Q)" },
      { external_id: 17, external_name: "Table 1.2.3. Real Gross Domestic Product by Major Type of Product, Quantity Indexes (A) (Q)" },
      { external_id: 18, external_name: "Table 1.2.4. Price Indexes for Gross Domestic Product by Major Type of Product (A) (Q)" },
      { external_id: 19, external_name: "Table 1.2.5. Gross Domestic Product by Major Type of Product (A) (Q)" },
      { external_id: 20, external_name: "Table 1.2.6. Real Gross Domestic Product by Major Type of Product, Chained Dollars (A) (Q)" },
      { external_id: 21, external_name: "Table 1.3.1. Percent Change From Preceding Period in Real Gross Value Added by Sector (A) (Q)" },
      { external_id: 22, external_name: "Table 1.3.3. Real Gross Value Added by Sector, Quantity Indexes (A) (Q)" },
      { external_id: 23, external_name: "Table 1.3.4. Price Indexes for Gross Value Added by Sector (A) (Q)" },
      { external_id: 24, external_name: "Table 1.3.5. Gross Value Added by Sector (A) (Q)" },
      { external_id: 25, external_name: "Table 1.3.6. Real Gross Value Added by Sector, Chained Dollars (A) (Q)" },
      { external_id: 26, external_name: "Table 1.4.1. Percent Change From Preceding Period in Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers (A) (Q)" },
      { external_id: 27, external_name: "Table 1.4.3. Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers, Quantity Indexes (A) (Q)" },
      { external_id: 28, external_name: "Table 1.4.4. Price Indexes for Gross Domestic Product, Gross Domestic Purchases, and Final Sales to Domestic Purchasers (A) (Q)" },
      { external_id: 29, external_name: "Table 1.4.5. Relation of Gross Domestic Product, Gross Domestic Purchases, and Final Sales to Domestic Purchasers (A) (Q)" },
      { external_id: 30, external_name: "Table 1.4.6. Relation of Real Gross Domestic Product, Real Gross Domestic Purchases, and Real Final Sales to Domestic Purchasers, Chained Dollars (A) (Q)" },
      { external_id: 31, external_name: "Table 1.5.1. Percent Change From Preceding Period in Real Gross Domestic Product, Expanded Detail (A) (Q)" },
      { external_id: 32, external_name: "Table 1.5.2. Contributions to Percent Change in Real Gross Domestic Product, Expanded Detail (A) (Q)" },
      { external_id: 33, external_name: "Table 1.5.3. Real Gross Domestic Product, Expanded Detail, Quantity Indexes (A) (Q)" },
      { external_id: 34, external_name: "Table 1.5.4. Price Indexes for Gross Domestic Product, Expanded Detail (A) (Q)" },
      { external_id: 35, external_name: "Table 1.5.5. Gross Domestic Product, Expanded Detail (A) (Q)" },
      { external_id: 36, external_name: "Table 1.5.6. Real Gross Domestic Product, Expanded Detail, Chained Dollars (A) (Q)" },
      { external_id: 37, external_name: "Table 1.6.4. Price Indexes for Gross Domestic Purchases (A) (Q)" },
      { external_id: 38, external_name: "Table 1.6.7. Percent Change From Preceding Period in Prices for Gross Domestic Purchases (A) (Q)" },
      { external_id: 39, external_name: "Table 1.6.8. Contributions to Percent Change in the Gross Domestic Purchases Price Index (A) (Q)" },
      { external_id: 40, external_name: "Table 1.7.1. Percent Change from Preceding Period in Real Gross Domestic Product, Real Gross National Product, and Real Net National Product (A) (Q)" },
      { external_id: 41, external_name: "Table 1.7.3. Real Gross Domestic Product, Real Gross National Product, and Real Net National Product, Quantity Indexes (A) (Q)" },
      { external_id: 42, external_name: "Table 1.7.4. Price Indexes for Gross Domestic Product, Gross National Product, and Net National Product (A) (Q)" },
      { external_id: 43, external_name: "Table 1.7.5. Relation of Gross Domestic Product, Gross National Product, Net National Product, National Income, and Personal Income (A) (Q)" },
      { external_id: 44, external_name: "Table 1.7.6. Relation of Real Gross Domestic Product, Real Gross National Product, and Real Net National Product, Chained Dollars (A) (Q)" },
      { external_id: 45, external_name: "Table 1.8.3. Command-Basis Real Gross Domestic Product and Gross National Product, Quantity Indexes (A) (Q)" },
      { external_id: 46, external_name: "Table 1.8.6. Command-Basis Real Gross Domestic Product and Gross National Product, Chained Dollars (A) (Q)" },
      { external_id: 47, external_name: "Table 1.9.3. Real Net Value Added by Sector, Quantity Indexes (A)" },
      { external_id: 48, external_name: "Table 1.9.4. Price Indexes for Net Value Added by Sector (A)" },
      { external_id: 49, external_name: "Table 1.9.5. Net Value Added by Sector (A)" },
      { external_id: 50, external_name: "Table 1.9.6. Real Net Value Added by Sector, Chained Dollars (A)" },
      { external_id: 51, external_name: "Table 1.10. Gross Domestic Income by Type of Income (A) (Q)" },
      { external_id: 52, external_name: "Table 1.11. Percentage Shares of Gross Domestic Income (A)" },
      { external_id: 53, external_name: "Table 1.12. National Income by Type of Income (A) (Q)" },
      { external_id: 54, external_name: "Table 1.13. National Income by Sector, Legal Form of Organization, and Type of Income (A)" },
      { external_id: 55, external_name: "Table 1.14. Gross Value Added of Domestic Corporate Business in Current Dollars and Gross Value Added of Nonfinancial Domestic Corporate Business in Current and Chained Dollars (A) (Q)" },
      { external_id: 56, external_name: "Table 1.15. Price, Costs, and Profit Per Unit of Real Gross Value Added of Nonfinancial Domestic Corporate Business (A) (Q)" },
      { external_id: 57, external_name: "Table 1.16. Sources and Uses of Private Enterprise Income (A)" },
      { external_id: 316, external_name: "Table 1.17.1. Percent Change From Preceding Period in Real Gross Domestic Product, Real Gross Domestic Income, and Other Major NIPA Aggregates (A) (Q)" },
      { external_id: 317, external_name: "Table 1.17.5. Gross Domestic Product, Gross Domestic Income, and Other Major NIPA Aggregates (A) (Q)" },
      { external_id: 318, external_name: "Table 1.17.6. Real Gross Domestic Product, Real Gross Domestic Income, and Other Major NIPA Aggregates, Chained Dollars (A) (Q)" },
      { external_id: 58, external_name: "Table 2.1. Personal Income and Its Disposition (A) (Q)" },
      { external_id: 59, external_name: "Table 2.2A. Wages and salaries by Industry (A) (Q)" },
      { external_id: 60, external_name: "Table 2.2B. Wages and salaries by Industry (A) (Q)" },
      { external_id: 61, external_name: "Table 2.3.1. Percent Change From Preceding Period in Real Personal Consumption Expenditures by Major Type of Product (A) (Q)" },
      { external_id: 62, external_name: "Table 2.3.2. Contributions to Percent Change in Real Personal Consumption Expenditures by Major Type of Product (A) (Q)" },
      { external_id: 63, external_name: "Table 2.3.3. Real Personal Consumption Expenditures by Major Type of Product, Quantity Indexes (A) (Q)" },
      { external_id: 64, external_name: "Table 2.3.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product (A) (Q)" },
      { external_id: 65, external_name: "Table 2.3.5. Personal Consumption Expenditures by Major Type of Product (A) (Q)" },
      { external_id: 66, external_name: "Table 2.3.6. Real Personal Consumption Expenditures by Major Type of Product, Chained Dollars (A) (Q)" },
      { external_id: 67, external_name: "Table 2.3.7. Percent Change from Preceding Period in Prices for Personal Consumption Expenditures by Major Type of Product (A) (Q)" },
      { external_id: 68, external_name: "Table 2.4.3. Real Personal Consumption Expenditures by Type of Product, Quantity Indexes (A)" },
      { external_id: 69, external_name: "Table 2.4.4. Price Indexes for Personal Consumption Expenditures by Type of Product (A)" },
      { external_id: 70, external_name: "Table 2.4.5. Personal Consumption Expenditures by Type of Product (A)" },
      { external_id: 71, external_name: "Table 2.4.6. Real Personal Consumption Expenditures by Type of Product, Chained Dollars (A)" },
      { external_id: 72, external_name: "Table 2.5.3 Real Personal Consumption Expenditures by Function, Quantity Indexes (A)" },
      { external_id: 73, external_name: "Table 2.5.4 Price Indexes for Personal Consumption Expenditures by Function (A)" },
      { external_id: 74, external_name: "Table 2.5.5 Personal Consumption Expenditures by Function (A)" },
      { external_id: 75, external_name: "Table 2.5.6 Real Personal Consumption Expenditures by Function, Chained Dollars (A)" },
      { external_id: 76, external_name: "Table 2.6. Personal Income and Its Disposition, Monthly (M)" },
      { external_id: 77, external_name: "Table 2.7A. Wages and salaries by Industry, Monthly (M)" },
      { external_id: 78, external_name: "Table 2.7B. Wages and salaries by Industry, Monthly (M)" },
      { external_id: 79, external_name: "Table 2.8.1. Percent Change From Preceding Period in Real Personal Consumption Expenditures by Major Type of Product, Monthly (M)" },
      { external_id: 80, external_name: "Table 2.8.3. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Quantity Indexes (M)" },
      { external_id: 81, external_name: "Table 2.8.4. Price Indexes for Personal Consumption Expenditures by Major Type of Product, Monthly (M)" },
      { external_id: 82, external_name: "Table 2.8.5. Personal Consumption Expenditures by Major Type of Product, Monthly (M)" },
      { external_id: 83, external_name: "Table 2.8.6. Real Personal Consumption Expenditures by Major Type of Product, Monthly, Chained Dollars (M)" },
      { external_id: 84, external_name: "Table 2.8.7. Percent Change from Preceding Period in Prices for Personal Consumption Expenditures by Major Type of Product, Monthly (M)" },
      { external_id: 85, external_name: "Table 2.9. Personal Income and Its Disposition by Households and by Nonprofit Institutions Serving Households (A)" },
      { external_id: 86, external_name: "Table 3.1. Government Current Receipts and Expenditures (A) (Q)" },
      { external_id: 87, external_name: "Table 3.2. Federal Government Current Receipts and Expenditures (A) (Q)" },
      { external_id: 88, external_name: "Table 3.3. State and Local Government Current Receipts and Expenditures (A) (Q)" },
      { external_id: 89, external_name: "Table 3.4. Personal Current Tax Receipts (A)" },
      { external_id: 90, external_name: "Table 3.5. Taxes on Production and Imports (A)" },
      { external_id: 91, external_name: "Table 3.6. Contributions for Government Social Insurance (A)" },
      { external_id: 92, external_name: "Table 3.7. Government Current Transfer Receipts (A)" },
      { external_id: 93, external_name: "Table 3.8. Current Surplus of Government Enterprises (A)" },
      { external_id: 94, external_name: "Table 3.9.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and Gross Investment (A) (Q)" },
      { external_id: 95, external_name: "Table 3.9.2. Contributions to Percent Change in Real Government Consumption Expenditures and Gross Investment (A) (Q)" },
      { external_id: 96, external_name: "Table 3.9.3. Real Government Consumption Expenditures and Gross Investment, Quantity Indexes (A) (Q)" },
      { external_id: 97, external_name: "Table 3.9.4. Price Indexes for Government Consumption Expenditures and Gross Investment (A) (Q)" },
      { external_id: 98, external_name: "Table 3.9.5. Government Consumption Expenditures and Gross Investment (A) (Q)" },
      { external_id: 99, external_name: "Table 3.9.6. Real Government Consumption Expenditures and Gross Investment, Chained Dollars (A) (Q)" },
      { external_id: 100, external_name: "Table 3.10.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and General Government Gross Output (A) (Q)" },
      { external_id: 101, external_name: "Table 3.10.3. Real Government Consumption Expenditures and General Government Gross Output, Quantity Indexes (A) (Q)" },
      { external_id: 102, external_name: "Table 3.10.4. Price Indexes for Government Consumption Expenditures and General Government Gross Output (A) (Q)" },
      { external_id: 103, external_name: "Table 3.10.5. Government Consumption Expenditures and General Government Gross Output (A) (Q)" },
      { external_id: 104, external_name: "Table 3.10.6. Real Government Consumption Expenditures and General Government Gross Output, Chained Dollars (A) (Q)" },
      { external_id: 105, external_name: "Table 3.11.1. Percent Change From Preceding Period in Real National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)" },
      { external_id: 106, external_name: "Table 3.11.3. Real National Defense Consumption Expenditures and Gross Investment by Type, Quantity Indexes (A) (Q)" },
      { external_id: 107, external_name: "Table 3.11.4. Price Indexes for National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)" },
      { external_id: 108, external_name: "Table 3.11.5. National Defense Consumption Expenditures and Gross Investment by Type (A) (Q)" },
      { external_id: 109, external_name: "Table 3.11.6. Real National Defense Consumption Expenditures and Gross Investment by Type, Chained Dollars (A) (Q)" },
      { external_id: 110, external_name: "Table 3.12. Government Social Benefits (A)" },
      { external_id: 111, external_name: "Table 3.13. Subsidies (A)" },
      { external_id: 112, external_name: "Table 3.14. Government Social Insurance Funds Current Receipts and Expenditures (A)" },
      { external_id: 113, external_name: "Table 3.15.1. Percent Change From Preceding Period in Real Government Consumption Expenditures and Gross Investment by Function (A)" },
      { external_id: 114, external_name: "Table 3.15.2. Contributions to Percent Change in Real Government Consumption Expenditures and Gross Investment by Function (A)" },
      { external_id: 115, external_name: "Table 3.15.3. Real Government Consumption Expenditures and Gross Investment by Function, Quantity Indexes (A)" },
      { external_id: 116, external_name: "Table 3.15.4. Price Indexes for Government Consumption Expenditures and Gross Investment by Function (A)" },
      { external_id: 117, external_name: "Table 3.15.5. Government Consumption Expenditures and Gross Investment by Function (A)" },
      { external_id: 118, external_name: "Table 3.15.6. Real Government Consumption Expenditures and Gross Investment by Function, Chained Dollars (A)" },
      { external_id: 119, external_name: "Table 3.16. Government Current Expenditures by Function (A)" },
      { external_id: 120, external_name: "Table 3.17. Selected Government Current and Capital Expenditures by Function (A)" },
      { external_id: 121, external_name: "Table 3.18A. Relation of Federal Government Current Receipts and Expenditures in the National Income and Product Accounts to the Consolidated Cash Statement, Fiscal Years and Quarters (A) (Q)" },
      { external_id: 122, external_name: "Table 3.18B. Relation of Federal Government Current Receipts and Expenditures in the National Income and Product Accounts to the Budget, Fiscal Years and Quarters (A) (Q)" },
      { external_id: 123, external_name: "Table 3.19. Relation of State and Local Government Current Receipts and Expenditures in the National Income and Product Accounts to Census Bureau  &quot;Government Finances&quot; Data, Fiscal Years (A)" },
      { external_id: 124, external_name: "Table 3.20. State Government Current Receipts and Expenditures (A)" },
      { external_id: 125, external_name: "Table 3.21. Local Government Current Receipts and Expenditures (A)" },
      { external_id: 126, external_name: "Table 3.22. Federal Government Current Receipts and Expenditures, Not Seasonally Adjusted (Q)" },
      { external_id: 127, external_name: "Table 3.23. State and Local Government Current Receipts and Expenditures, Not Seasonally Adjusted (Q)" },
      { external_id: 128, external_name: "Table 4.1. Foreign Transactions in the National Income and Product Accounts (A) (Q)" },
      { external_id: 129, external_name: "Table 4.2.1. Percent Change From Preceding Period in Real Exports and in Real Imports of Goods and Services by Type of Product (A) (Q)" },
      { external_id: 130, external_name: "Table 4.2.2. Contributions to Percent Change in Real Exports and in Real Imports of Goods and Services by Type of Product (A) (Q)" },
      { external_id: 131, external_name: "Table 4.2.3. Real Exports and Imports of Goods and Services by Type of Product, Quantity Indexes (A) (Q)" },
      { external_id: 132, external_name: "Table 4.2.4. Price Indexes for Exports and Imports of Goods and Services by Type of Product (A) (Q)" },
      { external_id: 133, external_name: "Table 4.2.5. Exports and Imports of Goods and Services by Type of Product (A) (Q)" },
      { external_id: 134, external_name: "Table 4.2.6. Real Exports and Imports of Goods and Services by Type of Product, Chained Dollars (A) (Q)" },
      { external_id: 135, external_name: "Table 4.3A. Relation of Foreign Transactions in the National Income and Product Accounts to the Corresponding Items in the International Transactions Accounts (A)" },
      { external_id: 136, external_name: "Table 4.3B. Relation of Foreign Transactions in the National Income and Product Accounts to the Corresponding Items in the International Transactions Accounts (A)" },
      { external_id: 137, external_name: "Table 5.1. Saving and Investment by Sector (A) (Q)" },
      { external_id: 138, external_name: "Table 5.2.3. Real Gross and Net Domestic Investment by Major Type, Quantity Indexes (A)" },
      { external_id: 139, external_name: "Table 5.2.5. Gross and Net Domestic Investment by Major Type (A)" },
      { external_id: 140, external_name: "Table 5.2.6. Real Gross and Net Domestic Investment by Major Type, Chained Dollars (A)" },
      { external_id: 141, external_name: "Table 5.3.1. Percent Change From Preceding Period in Real Private Fixed Investment by Type (A) (Q)" },
      { external_id: 142, external_name: "Table 5.3.2. Contributions to Percent Change in Real Private Fixed Investment by Type (A) (Q)" },
      { external_id: 143, external_name: "Table 5.3.3. Real Private Fixed Investment by Type, Quantity Indexes (A) (Q)" },
      { external_id: 144, external_name: "Table 5.3.4. Price Indexes for Private Fixed Investment by Type (A) (Q)" },
      { external_id: 145, external_name: "Table 5.3.5. Private Fixed Investment by Type (A) (Q)" },
      { external_id: 146, external_name: "Table 5.3.6. Real Private Fixed Investment by Type, Chained Dollars (A) (Q)" },
      { external_id: 147, external_name: "Table 5.4.1. Percent Change From Preceding Period in Real Private Fixed Investment in Structures by Type (A)" },
      { external_id: 148, external_name: "Table 5.4.2. Contributions to Percent Change in Real Private Fixed Investment in Structures by Type (A)" },
      { external_id: 149, external_name: "Table 5.4.3. Real Private Fixed Investment in Structures by Type, Quantity Indexes (A)" },
      { external_id: 150, external_name: "Table 5.4.4. Price Indexes for Private Fixed Investment in Structures by Type (A)" },
      { external_id: 151, external_name: "Table 5.4.5. Private Fixed Investment in Structures by Type (A)" },
      { external_id: 152, external_name: "Table 5.4.6. Real Private Fixed Investment in Structures by Type, Chained Dollars (A)" },
      { external_id: 153, external_name: "Table 5.5.1. Percent Change From Preceding Period in Real Private Fixed Investment in Equipment and Software by Type (A)" },
      { external_id: 154, external_name: "Table 5.5.2. Contributions to Percent Change in Real Private Fixed Investment in Equipment and Software by Type (A)" },
      { external_id: 155, external_name: "Table 5.5.3. Real Private Fixed Investment in Equipment and Software by Type, Quantity Indexes (A)" },
      { external_id: 156, external_name: "Table 5.5.4. Price Indexes for Private Fixed Investment in Equipment and Software by Type (A)" },
      { external_id: 157, external_name: "Table 5.5.5. Private Fixed Investment in Equipment and Software by Type (A)" },
      { external_id: 158, external_name: "Table 5.5.6. Real Private Fixed Investment in Equipment and Software by Type, Chained Dollars (A)" },
      { external_id: 159, external_name: "Table 5.6.5A. Change in Private Inventories by Industry (A) (Q)" },
      { external_id: 160, external_name: "Table 5.6.5B. Change in Private Inventories by Industry (A) (Q)" },
      { external_id: 161, external_name: "Table 5.6.6A. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)" },
      { external_id: 162, external_name: "Table 5.6.6B. Change in Real Private Inventories by Industry, Chained Dollars (A) (Q)" },
      { external_id: 163, external_name: "Table 5.7.5A. Private Inventories and Domestic Final Sales of Business by Industry (Q)" },
      { external_id: 164, external_name: "Table 5.7.5B. Private Inventories and Domestic Final Sales by Industry (Q)" },
      { external_id: 165, external_name: "Table 5.7.6A. Real Private Inventories and Real Domestic Final Sales of Business by Industry, Chained Dollars (Q)" },
      { external_id: 166, external_name: "Table 5.7.6B. Real Private Inventories and Real Domestic Final Sales by Industry, Chained Dollars (Q)" },
      { external_id: 167, external_name: "Table 5.7.9A. Implicit Price Deflators for Private Inventories by Industry (Q)" },
      { external_id: 168, external_name: "Table 5.7.9B. Implicit Price Deflators for Private Inventories by Industry (Q)" },
      { external_id: 169, external_name: "Table 5.8.3A. Real Gross Government Fixed Investment by Type, Quantity Indexes (A)" },
      { external_id: 170, external_name: "Table 5.8.3B. Real Gross Government Fixed Investment by Type, Quantity Indexes (A)" },
      { external_id: 171, external_name: "Table 5.8.4A. Price Indexes for Gross Government Fixed Investment by Type (A)" },
      { external_id: 172, external_name: "Table 5.8.4B. Price Indexes for Gross Government Fixed Investment by Type (A)" },
      { external_id: 173, external_name: "Table 5.8.5A. Gross Government Fixed Investment by Type (A)" },
      { external_id: 174, external_name: "Table 5.8.5B. Gross Government Fixed Investment by Type (A)" },
      { external_id: 175, external_name: "Table 5.8.6A. Real Gross Government Fixed Investment by Type, Chained Dollars (A)" },
      { external_id: 176, external_name: "Table 5.8.6B. Real Gross Government Fixed Investment by Type, Chained Dollars (A)" },
      { external_id: 177, external_name: "Table 5.9. Changes in Net Stock of Produced Assets (Fixed Assets and Inventories) (A)" },
      { external_id: 178, external_name: "Table 5.10. Capital Transfers Paid and Received, by Sector and by Type (A)" },
      { external_id: 179, external_name: "Table 6.1B. National Income Without Capital Consumption Adjustment by Industry (A) (Q)" },
      { external_id: 180, external_name: "Table 6.1C. National Income Without Capital Consumption Adjustment by Industry (A) (Q)" },
      { external_id: 181, external_name: "Table 6.1D. National Income Without Capital Consumption Adjustment by Industry (A) (Q)" },
      { external_id: 182, external_name: "Table 6.2A. Compensation of Employees by Industry (A)" },
      { external_id: 183, external_name: "Table 6.2B. Compensation of Employees by Industry (A)" },
      { external_id: 184, external_name: "Table 6.2C. Compensation of Employees by Industry (A)" },
      { external_id: 185, external_name: "Table 6.2D. Compensation of Employees by Industry (A)" },
      { external_id: 186, external_name: "Table 6.3A. Wage and Salary Accruals by Industry (A)" },
      { external_id: 187, external_name: "Table 6.3B. Wage and Salary Accruals by Industry (A)" },
      { external_id: 188, external_name: "Table 6.3C. Wage and Salary Accruals by Industry (A)" },
      { external_id: 189, external_name: "Table 6.3D. Wage and Salary Accruals by Industry (A)" },
      { external_id: 190, external_name: "Table 6.4A. Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 191, external_name: "Table 6.4B. Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 192, external_name: "Table 6.4C. Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 193, external_name: "Table 6.4D. Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 194, external_name: "Table 6.5A. Full-Time Equivalent Employees by Industry (A)" },
      { external_id: 195, external_name: "Table 6.5B. Full-Time Equivalent Employees by Industry (A)" },
      { external_id: 196, external_name: "Table 6.5C. Full-Time Equivalent Employees by Industry (A)" },
      { external_id: 197, external_name: "Table 6.5D. Full-Time Equivalent Employees by Industry (A)" },
      { external_id: 198, external_name: "Table 6.6A. Wage and Salary Accruals Per Full-Time Equivalent Employee by Industry (A)" },
      { external_id: 199, external_name: "Table 6.6B. Wage and Salary Accruals Per Full-Time Equivalent Employee by Industry (A)" },
      { external_id: 200, external_name: "Table 6.6C. Wage and Salary Accruals Per Full-Time Equivalent Employee by Industry (A)" },
      { external_id: 201, external_name: "Table 6.6D. Wage and Salary Accruals Per Full-Time Equivalent Employee by Industry (A)" },
      { external_id: 202, external_name: "Table 6.7A. Self-Employed Persons by Industry (A)" },
      { external_id: 203, external_name: "Table 6.7B. Self-Employed Persons by Industry (A)" },
      { external_id: 204, external_name: "Table 6.7C. Self-Employed Persons by Industry (A)" },
      { external_id: 205, external_name: "Table 6.7D. Self-Employed Persons by Industry (A)" },
      { external_id: 206, external_name: "Table 6.8A. Persons Engaged in Production by Industry (A)" },
      { external_id: 207, external_name: "Table 6.8B. Persons Engaged in Production by Industry (A)" },
      { external_id: 208, external_name: "Table 6.8C. Persons Engaged in Production by Industry (A)" },
      { external_id: 209, external_name: "Table 6.8D. Persons Engaged in Production by Industry (A)" },
      { external_id: 210, external_name: "Table 6.9B. Hours Worked by Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 211, external_name: "Table 6.9C. Hours Worked by Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 212, external_name: "Table 6.9D. Hours Worked by Full-Time and Part-Time Employees by Industry (A)" },
      { external_id: 213, external_name: "Table 6.10B. Employer Contributions for Government Social Insurance by Industry (A)" },
      { external_id: 214, external_name: "Table 6.10C. Employer Contributions for Government Social Insurance by Industry (A)" },
      { external_id: 215, external_name: "Table 6.10D. Employer Contributions for Government Social Insurance by Industry (A)" },
      { external_id: 216, external_name: "Table 6.11A. Employer Contributions for Employee Pension and Insurance Funds by Industry and by Type (A)" },
      { external_id: 217, external_name: "Table 6.11B. Employer Contributions for Employee Pension and Insurance Funds by Industry and by Type (A)" },
      { external_id: 218, external_name: "Table 6.11C. Employer Contributions for Employee Pension and Insurance Funds by Industry and by Type (A)" },
      { external_id: 219, external_name: "Table 6.11D. Employer Contributions for Employee Pension and Insurance Funds by Industry and by Type (A)" },
      { external_id: 220, external_name: "Table 6.12A. Nonfarm Proprietors' Income by Industry (A)" },
      { external_id: 221, external_name: "Table 6.12B. Nonfarm Proprietors' Income by Industry (A)" },
      { external_id: 222, external_name: "Table 6.12C. Nonfarm Proprietors' Income by Industry (A)" },
      { external_id: 223, external_name: "Table 6.12D. Nonfarm Proprietors' Income by Industry (A)" },
      { external_id: 224, external_name: "Table 6.13A. Noncorporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 225, external_name: "Table 6.13B. Noncorporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 226, external_name: "Table 6.13C. Noncorporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 227, external_name: "Table 6.13D. Noncorporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 228, external_name: "Table 6.14A. Inventory Valuation Adjustment to Nonfarm Incomes by Legal Form of Organization and by Industry (A)" },
      { external_id: 229, external_name: "Table 6.14B. Inventory Valuation Adjustment to Nonfarm Incomes by Legal Form of Organization and by Industry (A)" },
      { external_id: 230, external_name: "Table 6.14C. Inventory Valuation Adjustment to Nonfarm Incomes by Legal Form of Organization and by Industry (A)" },
      { external_id: 231, external_name: "Table 6.14D. Inventory Valuation Adjustment to Nonfarm Incomes by Legal Form of Organization and by Industry (A)" },
      { external_id: 232, external_name: "Table 6.15A. Net Interest by Industry (A)" },
      { external_id: 233, external_name: "Table 6.15B. Net Interest by Industry (A)" },
      { external_id: 234, external_name: "Table 6.15C. Net Interest by Industry (A)" },
      { external_id: 235, external_name: "Table 6.15D. Net Interest by Industry (A)" },
      { external_id: 236, external_name: "Table 6.16A. Corporate Profits by Industry (A)" },
      { external_id: 237, external_name: "Table 6.16B. Corporate Profits by Industry (A) (Q)" },
      { external_id: 238, external_name: "Table 6.16C. Corporate Profits by Industry (A) (Q)" },
      { external_id: 239, external_name: "Table 6.16D. Corporate Profits by Industry (A) (Q)" },
      { external_id: 240, external_name: "Table 6.17A. Corporate Profits Before Tax by Industry (A)" },
      { external_id: 241, external_name: "Table 6.17B. Corporate Profits Before Tax by Industry (A)" },
      { external_id: 242, external_name: "Table 6.17C. Corporate Profits Before Tax by Industry (A)" },
      { external_id: 243, external_name: "Table 6.17D. Corporate Profits Before Tax by Industry (A)" },
      { external_id: 244, external_name: "Table 6.18A. Taxes on Corporate Income by Industry (A)" },
      { external_id: 245, external_name: "Table 6.18B. Taxes on Corporate Income by Industry (A)" },
      { external_id: 246, external_name: "Table 6.18C. Taxes on Corporate Income by Industry (A)" },
      { external_id: 247, external_name: "Table 6.18D. Taxes on Corporate Income by Industry (A)" },
      { external_id: 248, external_name: "Table 6.19A. Corporate Profits After Tax by Industry (A)" },
      { external_id: 249, external_name: "Table 6.19B. Corporate Profits After Tax by Industry (A)" },
      { external_id: 250, external_name: "Table 6.19C. Corporate Profits After Tax by Industry (A)" },
      { external_id: 251, external_name: "Table 6.19D. Corporate Profits After Tax by Industry (A)" },
      { external_id: 252, external_name: "Table 6.20A. Net Corporate Dividend Payments by Industry (A)" },
      { external_id: 253, external_name: "Table 6.20B. Net Corporate Dividend Payments by Industry (A)" },
      { external_id: 254, external_name: "Table 6.20C. Net Corporate Dividend Payments by Industry (A)" },
      { external_id: 255, external_name: "Table 6.20D. Net Corporate Dividend Payments by Industry (A)" },
      { external_id: 256, external_name: "Table 6.21A. Undistributed Corporate Profits by Industry (A)" },
      { external_id: 257, external_name: "Table 6.21B. Undistributed Corporate Profits by Industry (A)" },
      { external_id: 258, external_name: "Table 6.21C. Undistributed Corporate Profits by Industry (A)" },
      { external_id: 259, external_name: "Table 6.21D. Undistributed Corporate Profits by Industry (A)" },
      { external_id: 260, external_name: "Table 6.22A. Corporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 261, external_name: "Table 6.22B. Corporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 262, external_name: "Table 6.22C. Corporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 263, external_name: "Table 6.22D. Corporate Capital Consumption Allowances by Industry (A)" },
      { external_id: 264, external_name: "Table 7.1. Selected Per Capita Income and Product Series in Current and Chained Dollars (A) (Q)" },
      { external_id: 265, external_name: "Table 7.2.1A. Percent Change From Preceding Period in Real Auto Output (A) (Q)" },
      { external_id: 266, external_name: "Table 7.2.1B. Percent Change from Preceding Period in Real Motor Vehicle Output (A) (Q)" },
      { external_id: 267, external_name: "Table 7.2.3A. Real Auto Output, Quantity Indexes (A) (Q)" },
      { external_id: 268, external_name: "Table 7.2.3B. Real Motor Vehicle Output, Quantity Indexes (A) (Q)" },
      { external_id: 269, external_name: "Table 7.2.4A. Price Indexes for Auto Output (A) (Q)" },
      { external_id: 270, external_name: "Table 7.2.4B. Price Indexes for Motor Vehicle Output (A) (Q)" },
      { external_id: 271, external_name: "Table 7.2.5A. Auto Output (A) (Q)" },
      { external_id: 272, external_name: "Table 7.2.5B. Motor Vehicle Output (A) (Q)" },
      { external_id: 273, external_name: "Table 7.2.6B. Real Motor Vehicle Output, Chained Dollars (A) (Q)" },
      { external_id: 274, external_name: "Table 7.3.3. Real Farm Sector Output, Real Gross Value Added, and Real Net Value Added, Quantity Indexes (A)" },
      { external_id: 275, external_name: "Table 7.3.4. Price Indexes for Farm Sector Output, Gross Value Added, and Net Value Added (A)" },
      { external_id: 276, external_name: "Table 7.3.5. Farm Sector Output, Gross Value Added, and Net Value Added (A)" },
      { external_id: 277, external_name: "Table 7.3.6. Real Farm Sector Output, Real Gross Value Added, and Real Net Value Added, Chained Dollars (A)" },
      { external_id: 278, external_name: "Table 7.4.3. Real Housing Sector Output, Real Gross Value Added, and Real Net Value Added, Quantity Indexes (A)" },
      { external_id: 279, external_name: "Table 7.4.4. Price Indexes for Housing Sector Output, Gross Value Added, and Net Value Added (A)" },
      { external_id: 280, external_name: "Table 7.4.5. Housing Sector Output, Gross Value Added, and Net Value Added (A)" },
      { external_id: 281, external_name: "Table 7.4.6. Real Housing Sector Output, Real Gross Value Added, and Real Net Value Added, Chained Dollars (A)" },
      { external_id: 282, external_name: "Table 7.5. Consumption of Fixed Capital by Legal Form of Organization and Type of Income (A) (Q)" },
      { external_id: 283, external_name: "Table 7.6. Capital Consumption Adjustment by Legal Form of Organization and Type of Adjustment (A)" },
      { external_id: 284, external_name: "Table 7.7. Business Current Transfer Payments by Type (A)" },
      { external_id: 285, external_name: "Table 7.8. Supplements to Wages and Salaries by Type (A)" },
      { external_id: 286, external_name: "Table 7.9. Rental Income of Persons by Legal Form of Organization and by Type of Income (A)" },
      { external_id: 287, external_name: "Table 7.10. Dividends Paid and Received by Sector (A)" },
      { external_id: 288, external_name: "Table 7.11. Interest Paid and Received by Sector and Legal Form of Organization (A)" },
      { external_id: 289, external_name: "Table 7.12. Imputations in the National Income and Product Accounts (A)" },
      { external_id: 290, external_name: "Table 7.13. Relation of Consumption of Fixed Capital in the National Income and Product Accounts to Depreciation and Amortization as Published by the Internal Revenue Service (A)" },
      { external_id: 291, external_name: "Table 7.14. Relation of Nonfarm Proprietors' Income in the National Income and Product Accounts to Corresponding Measures as Published by the Internal Revenue Service (A)" },
      { external_id: 292, external_name: "Table 7.15. Relation of Net Farm Income in the National Income and Product Accounts to Net Farm Income as Published by the U.S. Department of Agriculture (A)" },
      { external_id: 293, external_name: "Table 7.16. Relation of Corporate Profits, Taxes, and Dividends in the National Income and Product Accounts to Corresponding Measures as Published by the Internal Revenue Service (A)" },
      { external_id: 294, external_name: "Table 7.17. Relation of Monetary Interest Paid and Received in the National Income and Product Accounts to Corresponding Measures as Published by the Internal Revenue Service (A)" },
      { external_id: 295, external_name: "Table 7.18. Relation of Wages and Salaries in the National Income and Product Accounts to Wages and Salaries as Published by the Bureau of Labor Statistics (A)" },
      { external_id: 296, external_name: "Table 7.20. Comparison of Income and Outlays of Nonprofit Institutions Serving Households with Revenue and Expenses as Published by the Internal Revenue Service (A)" }]
    }]
  }]

SOURCES.each do |source|
  Source.where(name: source[:name]).first_or_create(source)
end
