SOURCES = [
  { name: 'Bureau of Economic Analysis', datasets_attributes: [
    { name: 'Fixed Assets', external_tables_attributes: [
      { external_id: 16, external_name: "Table 1.1. Current-Cost Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 17, external_name: "Table 1.2. Chain-Type Quantity Indexes for Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 86, external_name: "Table 1.3. Current-Cost Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 87, external_name: "Table 1.4. Chain-Type Quantity Indexes for Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 96, external_name: "Table 1.5. Investment in Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 97, external_name: "Table 1.6. Chain-Type Quantity Indexes for Investment in Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 105, external_name: "Table 1.7. Current-Cost Other Changes in Volume of Assets for Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 124, external_name: "Table 1.8. Historical-Cost Other Changes in Volume of Assets for Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 125, external_name: "Table 1.9. Current-Cost Average Age at Yearend of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 18, external_name: "Table 2.1. Current-Cost Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 19, external_name: "Table 2.2. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 42, external_name: "Table 2.3. Historical-Cost Net Stock of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 65, external_name: "Table 2.4. Current-Cost Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 66, external_name: "Table 2.5. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 67, external_name: "Table 2.6. Historical-Cost Depreciation of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 51, external_name: "Table 2.7. Investment in Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 52, external_name: "Table 2.8. Chain-Type Quantity Indexes for Investment in Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 106, external_name: "Table 2.9. Current-Cost Average Age at Yearend of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 107, external_name: "Table 2.10. Historical-Cost Average Age at Yearend of Private Fixed Assets, Equipment, Structures, and Intellectual Property Products by Type (A)" },
      { external_id: 21, external_name: "Table 3.1E. Current-Cost Net Stock of Private Equipment by Industry (A)" },
      { external_id: 126, external_name: "Table 3.1ESI. Current-Cost Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 127, external_name: "Table 3.1I. Current-Cost Net Stock of Intellectual Property Products by Industry (A)" },
      { external_id: 22, external_name: "Table 3.1S. Current-Cost Net Stock of Private Structures by Industry (A)" },
      { external_id: 24, external_name: "Table 3.2E. Chain-Type Quantity Indexes for Net Stock of Private Equipment by Industry (A)" },
      { external_id: 128, external_name: "Table 3.2ESI. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 129, external_name: "Table 3.2I. Chain-Type Quantity Indexes for Net Stock of Intellectual Property Products by Industry (A)" },
      { external_id: 25, external_name: "Table 3.2S. Chain-Type Quantity Indexes for Net Stock of Private Structures by Industry (A)" },
      { external_id: 44, external_name: "Table 3.3E. Historical-Cost Net Stock of Private Equipment by Industry (A)" },
      { external_id: 130, external_name: "Table 3.3ESI. Historical-Cost Net Stock of Private Fixed Assets by Industry (A)" },
      { external_id: 131, external_name: "Table 3.3I. Historical-Cost Net Stock of Private Intellectual Property Products by Industry (A)" },
      { external_id: 45, external_name: "Table 3.3S. Historical-Cost Net Stock of Private Structures by Industry (A)" },
      { external_id: 69, external_name: "Table 3.4E. Current-Cost Depreciation of Private Equipment by Industry (A)" },
      { external_id: 132, external_name: "Table 3.4ESI. Current-Cost Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 133, external_name: "Table 3.4I. Current-Cost Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 70, external_name: "Table 3.4S. Current-Cost Depreciation of Private Structures by Industry (A)" },
      { external_id: 72, external_name: "Table 3.5E. Chain-Type Quantity Indexes for Depreciation of Private Equipment by Industry (A)" },
      { external_id: 134, external_name: "Table 3.5ESI. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 135, external_name: "Table 3.5I. Chain-Type Quantity Indexes for Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 73, external_name: "Table 3.5S. Chain-Type Quantity Indexes for Depreciation of Private Structures by Industry (A)" },
      { external_id: 75, external_name: "Table 3.6E. Historical-Cost Depreciation of Private Equipment by Industry (A)" },
      { external_id: 136, external_name: "Table 3.6ESI. Historical-Cost Depreciation of Private Fixed Assets by Industry (A)" },
      { external_id: 137, external_name: "Table 3.6I. Historical-Cost Depreciation of Private Intellectual Property Products by Industry (A)" },
      { external_id: 76, external_name: "Table 3.6S. Historical-Cost Depreciation of Private Structures by Industry (A)" },
      { external_id: 54, external_name: "Table 3.7E. Investment in Private Equipment by Industry (A)" },
      { external_id: 138, external_name: "Table 3.7ESI. Investment in Private Fixed Assets by Industry (A)" },
      { external_id: 139, external_name: "Table 3.7I. Investment in Private Intellectual Property Products by Industry (A)" },
      { external_id: 55, external_name: "Table 3.7S. Investment in Private Structures by Industry (A)" },
      { external_id: 57, external_name: "Table 3.8E. Chain-Type Quantity Indexes for Investment in Private Equipment by Industry (A)" },
      { external_id: 140, external_name: "Table 3.8ESI. Chain-Type Quantity Indexes for Investment in Private Fixed Assets by Industry (A)" },
      { external_id: 141, external_name: "Table 3.8I. Chain-Type Quantity Indexes for Investment in Private Intellectual Property Products by Industry (A)" },
      { external_id: 58, external_name: "Table 3.8S. Chain-Type Quantity Indexes for Investment in Private Structures by Industry (A)" },
      { external_id: 108, external_name: "Table 3.9E. Current-Cost Average Age at Yearend of Private Equipment by Industry (A)" },
      { external_id: 142, external_name: "Table 3.9ESI. Current-Cost Average Age at Yearend of Private Fixed Assets by Industry (A)" },
      { external_id: 143, external_name: "Table 3.9I. Current-Cost Average Age at Yearend of Private Intellectual Property Products by Industry (A)" },
      { external_id: 110, external_name: "Table 3.9S. Current-Cost Average Age at Yearend of Private Structures by Industry (A)" },
      { external_id: 111, external_name: "Table 3.10E. Historical-Cost Average Age at Yearend of Private Equipment by Industry (A)" },
      { external_id: 144, external_name: "Table 3.10ESI. Historical-Cost Average Age at Yearend of Private Fixed Assets by Industry (A)" },
      { external_id: 145, external_name: "Table 3.10I. Historical-Cost Average Age at Yearend of Private Intellectual Property Products by Industry (A)" },
      { external_id: 113, external_name: "Table 3.10S. Historical-Cost Average Age at Yearend of Private Structures by Industry (A)" },
      { external_id: 26, external_name: "Table 4.1. Current-Cost Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 27, external_name: "Table 4.2. Chain-Type Quantity Indexes for Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 46, external_name: "Table 4.3. Historical-Cost Net Stock of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 77, external_name: "Table 4.4. Current-Cost Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 78, external_name: "Table 4.5. Chain-Type Quantity Indexes for Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 79, external_name: "Table 4.6. Historical-Cost Depreciation of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 59, external_name: "Table 4.7. Investment in Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 60, external_name: "Table 4.8. Chain-Type Quantity Indexes for Investment in Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 114, external_name: "Table 4.9. Current-Cost Average Age at Yearend of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 115, external_name: "Table 4.10. Historical-Cost Average Age at Yearend of Private Nonresidential Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 28, external_name: "Table 5.1. Current-Cost Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 29, external_name: "Table 5.2. Chain-Type Quantity Indexes for Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 47, external_name: "Table 5.3. Historical-Cost Net Stock of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 88, external_name: "Table 5.4. Current-Cost Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 89, external_name: "Table 5.5. Chain-Type Quantity Indexes for Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 90, external_name: "Table 5.6. Historical-Cost Depreciation of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 98, external_name: "Table 5.7. Investment in Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 99, external_name: "Table 5.8. Chain-Type Quantity Indexes for Investment in Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 116, external_name: "Table 5.9. Current-Cost Average Age at Yearend of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 117, external_name: "Table 5.10. Historical-Cost Average Age at Yearend of Residential Fixed Assets by Type of Owner, Legal Form of Organization, and Tenure Group (A)" },
      { external_id: 41, external_name: "Table 6.1. Current-Cost Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 48, external_name: "Table 6.2. Chain-Type Quantity Indexes for Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 49, external_name: "Table 6.3. Historical-Cost Net Stock of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 80, external_name: "Table 6.4. Current-Cost Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 81, external_name: "Table 6.5. Chain-Type Quantity Indexes for Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 82, external_name: "Table 6.6. Historical-Cost Depreciation of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 61, external_name: "Table 6.7. Investment in Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 62, external_name: "Table 6.8. Chain-Type Quantity Indexes for Investment in Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 118, external_name: "Table 6.9. Current-Cost Average Age at Yearend of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 119, external_name: "Table 6.10. Historical-Cost Average Age at Yearend of Private Fixed Assets by Industry Group and Legal Form of Organization (A)" },
      { external_id: 35, external_name: "Table 7.1A. Current-Cost Net Stock of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 30, external_name: "Table 7.1B. Current-Cost Net Stock of Government Fixed Assets (A)" },
      { external_id: 36, external_name: "Table 7.2A. Chain-Type Quantity Indexes for Net Stock of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 31, external_name: "Table 7.2B. Chain-Type Quantity Indexes for Net Stock of Government Fixed Assets (A)" },
      { external_id: 91, external_name: "Table 7.3A. Current-Cost Depreciation of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 92, external_name: "Table 7.3B. Current-Cost Depreciation of Government Fixed Assets (A)" },
      { external_id: 93, external_name: "Table 7.4A. Chain-Type Quantity Indexes for Depreciation of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 94, external_name: "Table 7.4B. Chain-Type Quantity Indexes for Depreciation of Government Fixed Assets (A)" },
      { external_id: 100, external_name: "Table 7.5A. Investment in Government Fixed Assets, 1901-1996 (A)" },
      { external_id: 101, external_name: "Table 7.5B. Investment in Government Fixed Assets (A)" },
      { external_id: 102, external_name: "Table 7.6A. Chain-Type Quantity Indexes for Investment in Government Fixed Assets, 1901-1996 (A)" },
      { external_id: 103, external_name: "Table 7.6B. Chain-Type Quantity Indexes for Investment in Government Fixed Assets (A)" },
      { external_id: 120, external_name: "Table 7.7A. Current-Cost Average Age at Yearend of Government Fixed Assets, 1925-1996 (A)" },
      { external_id: 121, external_name: "Table 7.7B. Current-Cost Average Age at Yearend of Government Fixed Assets (A)" },
      { external_id: 32, external_name: "Table 8.1. Current-Cost Net Stock of Consumer Durable Goods (A)" },
      { external_id: 33, external_name: "Table 8.2. Chain-Type Quantity Indexes for Net Stock of Consumer Durable Goods (A)" },
      { external_id: 50, external_name: "Table 8.3. Historical-Cost Net Stock of Consumer Durable Goods (A)" },
      { external_id: 83, external_name: "Table 8.4. Current-Cost Depreciation of Consumer Durable Goods (A)" },
      { external_id: 84, external_name: "Table 8.5. Chain-Type Quantity Indexes for Depreciation of Consumer Durable Goods (A)" },
      { external_id: 85, external_name: "Table 8.6. Historical-Cost Depreciation of Consumer Durable Goods (A)" },
      { external_id: 63, external_name: "Table 8.7. Investment in Consumer Durable Goods (A)" },
      { external_id: 64, external_name: "Table 8.8. Chain-Type Quantity Indexes for Investment in Consumer Durable Goods (A)" },
      { external_id: 122, external_name: "Table 8.9. Current-Cost Average Age at Yearend of Consumer Durable Goods (A)" },
      { external_id: 123, external_name: "Table 8.10. Historical-Cost Average Age at Yearend of Consumer Durable Goods (A)" },
      { external_id: 34, external_name: "Table 9.1. Real Net Stock of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 95, external_name: "Table 9.2. Real Depreciation of Fixed Assets and Consumer Durable Goods (A)" },
      { external_id: 104, external_name: "Table 9.3. Real Investment in Fixed Assets and Consumer Durable Goods (A)" }]
    }]
  }
]

SOURCES.each do |source|
  Source.where(name: source[:name]).first_or_create(source)
end
